on:
  pull_request_target:
    types:
      - opened
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: merge
        uses: "pascalgn/automerge-action@v0.13.1"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: ""
